spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
  profiles:
    active: public
  aop:
    proxy-target-class: true

mybatis:
  mapper-locations: classpath*:mybatis/**/*.xml

logging:
  config: classpath:log4j2.yml



